### ISSUE TITLE
Create replacement for CocoaDocs

### ISSUE THREAD

**Issue by lgauthier** [metova/MetovaTestKit#23]
Ever since the end of May this year, CocoaDocs no longer generates and hosts documentation for newly submitted pod versions. [Read more here](http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/).

We need to figure out a simple way of generating and hosting documentation for new versions ourselves. Generating the documentation is fairly simple--we can just use [jazzy](https://github.com/realm/jazzy), which is the tool CocoaDocs used. The trickier parts that we need to address are:

- Automate documentation generation each time we submit a new version.
- Hosting the documentation ourselves.

I've looked into it a little bit so far, and I think we could potentially simply host our docs within our GitHub repo to make publishing new docs easy, but we'd want to automate this process. You can check out the branch I've started to see what I've done so far:

- [Branch](https://github.com/metova/MetovaTestKit/tree/feature/documentation)
- [Docs Preview](https://cdn.rawgit.com/metova/MetovaTestKit/feature/documentation/Documentation/1.1.0/index.html) (Using rawgit.com)

So far, the main problems with what I've done on that branch are:
- We have to remember to run `jazzy` each time before submitting a new version.
- We have to remember to update the documentation link in the README so it references the index page of the latest docset.
- The documentation badge isn't working on the README. This may be a simple fix though.

**Comment by schrismartin** [comment]
Suggestion: Build using github-pages. 

- Pushes to `master` should trigger a travis build step that generates docs and pushes them to a `gh-pages` branch.
- GitHub Pages can be configured to redirect somewhere, like `docs.metova.com`. Any other repos with pages will then be automatically hosted at `docs.metova.com/repo-name`.
