### ISSUE TITLE
Update for Swift 4.2

### ISSUE THREAD

**Issue by addisonwebb** [metova/MetovaTestKit#32]
When trying to update a project to Swift 4.2, Xcode shows several errors for MetovaTestKit that need to be fixed to build app with Swift 4.2.

![screen shot 2018-09-25 at 12 41 53 pm](https://user-images.githubusercontent.com/3932168/46034796-865ff900-c0cf-11e8-9522-7de8cba8038e.png)

**Comment by nhgrif** [comment]
Resolved by #34
