### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [metova/MetovaTestKit#9]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by nhgrif** [comment]
The [swift3](https://github.com/metova/MetovaTestKit/tree/feature/swift3) branch should be compatible.  I just need to get the travis build passing.  Looks like it's currently failing to lint correctly despite it building perfectly fine locally.

**Comment by lfarah** [comment]
@nhgrif since Xcode 8 is out, I think it's worth merging into Master...

**Comment by nhgrif** [comment]
This is updated now.  Updating in CocoaPods repo currently.

**Comment by lfarah** [comment]
Thanks @nhgrif, you're awesome! 🎉
